const IMAGE = []
// const backgrounds = ['../../assets/body/body.png']
const bodies = [
    'assets/body/BODY_1.png',
    'assets/body/BODY_2.png',
    'assets/body/BODY_3.png',
    'assets/body/BODY_4.png',
    'assets/body/BODY_5.png',
    'assets/body/BODY_6.png',
    'assets/body/BODY_7.png',
    'assets/body/BODY_8.png',
    'assets/body/BODY_9.png',
    'assets/body/BODY_10.png',
    'assets/body/BODY_11.png',
    'assets/body/BODY_12.png',
    'assets/body/BODY_13.png',
    'assets/body/BODY_14.png',
    'assets/body/BODY_15.png',
    'assets/body/BODY_16.png',
    'assets/body/BODY_17.png',
    'assets/body/BODY_18.png',
    'assets/body/BODY_19.png',
    'assets/body/BODY_20.png',
    'assets/body/BODY_21.png',
]

const noses = [
    'assets/nose/NOSE_1.png',
    'assets/nose/NOSE_2.png',
    'assets/nose/NOSE_3.png',
    'assets/nose/NOSE_4.png',
    'assets/nose/NOSE_5.png',
    'assets/nose/NOSE_6.png',
    'assets/nose/NOSE_7.png',
    'assets/nose/NOSE_8.png',
]

const hairs = [
    'assets/hair/HAIR_1.png',
    'assets/hair/HAIR_2.png',
    'assets/hair/HAIR_3.png',
    'assets/hair/HAIR_4.png',
    'assets/hair/HAIR_5.png',
    'assets/hair/HAIR_6.png',
    'assets/hair/HAIR_7.png',
    'assets/hair/HAIR_8.png',
    'assets/hair/HAIR_9.png',
    'assets/hair/HAIR_10.png',
    'assets/hair/HAIR_11.png',
    'assets/hair/HAIR_12.png',
    'assets/hair/HAIR_13.png',
    'assets/hair/HAIR_14.png',
    'assets/hair/HAIR_15.png',
    'assets/hair/HAIR_16.png',
    'assets/hair/HAIR_17.png',
    'assets/hair/HAIR_18.png',
]

const faces = [
    'assets/face/FACE_1.png',
    'assets/face/FACE_2.png',
    'assets/face/FACE_3.png',
    'assets/face/FACE_4.png',
    'assets/face/FACE_5.png',
    'assets/face/FACE_6.png',
    'assets/face/FACE_7.png',
    'assets/face/FACE_8.png',
    'assets/face/FACE_9.png',
    'assets/face/FACE_10.png',
    'assets/face/FACE_11.png',
    'assets/face/FACE_12.png',
    'assets/face/FACE_13.png',
    'assets/face/FACE_14.png',
    'assets/face/FACE_15.png',
    'assets/face/FACE_16.png',
    'assets/face/FACE_17.png',
    'assets/face/FACE_18.png',
    'assets/face/FACE_19.png',
    'assets/face/FACE_20.png',
    'assets/face/FACE_21.png',
    'assets/face/FACE_22.png',
    'assets/face/FACE_23.png',
    'assets/face/FACE_24.png',
    'assets/face/FACE_25.png',
    'assets/face/FACE_26.png',
    'assets/face/FACE_27.png',
    'assets/face/FACE_28.png',
    'assets/face/FACE_29.png',
    'assets/face/FACE_30.png',
    'assets/face/FACE_31.png',
    'assets/face/FACE_32.png',
]

const mouths = [
    'assets/mouth/MOUTH_1.png',
    'assets/mouth/MOUTH_2.png',
    'assets/mouth/MOUTH_3.png',
    'assets/mouth/MOUTH_4.png',
    'assets/mouth/MOUTH_5.png',
    'assets/mouth/MOUTH_6.png',
    'assets/mouth/MOUTH_7.png',
    'assets/mouth/MOUTH_8.png',
    'assets/mouth/MOUTH_9.png',
    'assets/mouth/MOUTH_10.png',
    'assets/mouth/MOUTH_11.png',
    'assets/mouth/MOUTH_12.png',
]

const eyes = [
    'assets/eye/EYE_1.png',
    'assets/eye/EYE_2.png',
    'assets/eye/EYE_3.png',
    'assets/eye/EYE_4.png',
    'assets/eye/EYE_5.png',
    'assets/eye/EYE_6.png',
    'assets/eye/EYE_7.png',
    'assets/eye/EYE_8.png',
    'assets/eye/EYE_9.png',
    'assets/eye/EYE_10.png',
    'assets/eye/EYE_11.png',
    'assets/eye/EYE_12.png',
    'assets/eye/EYE_13.png',
    'assets/eye/EYE_14.png',
    'assets/eye/EYE_15.png',
    'assets/eye/EYE_16.png',
]

// const COLOR = []

export default {
    IMAGE,
    bodies,
    noses,
    hairs,
    faces,
    mouths,
    eyes,
}
